import { readFile, writeFile } from 'node:fs/promises';
import { build } from 'esbuild';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export async function bundleGame() {
  const result = await build({
    absWorkingDir: root,
    entryPoints: ['src/main.js'],
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'browser',
    target: ['es2022'],
    minify: true,
    legalComments: 'inline',
  });
  const shell = await readFile(resolve(root, 'src/shell.html'), 'utf8');
  const css = await readFile(resolve(root, 'src/styles.css'), 'utf8');
  const image = await readFile(resolve(root, 'src/assets/bia-pilot.webp'));
  const js = result.outputFiles[0].text.replaceAll('</script', '<\\/script');
  for (const marker of ['/* BUILD:STYLES */', '/* BUILD:GAME */', 'BUILD:PILOT'])
    if (!shell.includes(marker)) throw new Error(`Missing build marker: ${marker}`);
  return (
    '<!-- GENERATED from src/. Run npm run build. Do not edit this file. -->\n' +
    shell
      .replace('/* BUILD:STYLES */', () => css)
      .replace('/* BUILD:GAME */', () => js)
      .replaceAll('BUILD:PILOT', 'data:image/webp;base64,' + image.toString('base64'))
  );
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const html = await bundleGame();
  if (process.argv.includes('--check')) {
    const actual = await readFile(resolve(root, 'index.html'), 'utf8').catch(() => '');
    if (actual !== html)
      throw new Error('index.html differs from src/. Run npm run build and commit the output.');
    console.log('Build is reproducible and synchronized.');
  } else {
    await writeFile(resolve(root, 'index.html'), html);
    console.log(`index.html generated (${Buffer.byteLength(html)} bytes).`);
  }
}
